AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0
Description: IAM User creation template 
Parameters:
  Password:
    NoEcho: 'true'
    Type: String
    Description: New IAM account password
    MinLength: '1'
    MaxLength: '41'
    ConstraintDescription: the password must be between 1 and 41 characters
Resources:
  CFNUser:
    Type: AWS::IAM::User
    
  CFNKeys:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref 'CFNUser'

  AppBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: cfnbucketaroontrer
      VersioningConfiguration:
        Status: Suspended
   

  mybucketpolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AppBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: FullAccess
            Action: 'S3:*'
            Effect: Allow
            Resource: 
              - !Sub "arn:aws:s3:::${AppBucket}"
              - !Sub "arn:aws:s3:::${AppBucket}/*"
            Principal:
              AWS:
                - !GetAtt CFNUser.Arn
          


Outputs:
  AccessKey:
    Value: !Ref 'CFNKeys'
    Description: AWSAccessKeyId of new user
  SecretKey:
    Value: !GetAtt [CFNKeys, SecretAccessKey]
    Description: AWSSecretAccessKey of new user
